namespace Valkey.Glide;

/// <summary>
/// Constants representing values used in Valkey Stream commands.
/// </summary>
internal static class StreamConstants
{
    /// <summary>
    /// The "~" value used with the MAXLEN option.
    /// </summary>
    internal static readonly ValkeyValue ApproximateMaxLen = "~";

    /// <summary>
    /// The "*" value used with the XADD command.
    /// </summary>
    internal static readonly ValkeyValue AutoGeneratedId = "*";

    /// <summary>
    /// The "$" value used in the XGROUP command. Indicates reading only new messages from the stream.
    /// </summary>
    internal static readonly ValkeyValue NewMessages = "$";

    /// <summary>
    /// The "0" value used in the XGROUP command. Indicates reading all messages from the stream.
    /// </summary>
    internal static readonly ValkeyValue AllMessages = "0";

    /// <summary>
    /// The "-" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the minimum message ID from the stream.
    /// </summary>
    internal static readonly ValkeyValue ReadMinValue = "-";

    /// <summary>
    /// The "+" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the maximum message ID from the stream.
    /// </summary>
    internal static readonly ValkeyValue ReadMaxValue = "+";

    /// <summary>
    /// The ">" value used in the XREADGROUP command. Use this to read messages that have not been delivered to a consumer group.
    /// </summary>
    internal static readonly ValkeyValue UndeliveredMessages = ">";

    internal static readonly ValkeyValue Consumers = "CONSUMERS";

    internal static readonly ValkeyValue Count = "COUNT";

    internal static readonly ValkeyValue Create = "CREATE";

    internal static readonly ValkeyValue DeleteConsumer = "DELCONSUMER";

    internal static readonly ValkeyValue Destroy = "DESTROY";

    internal static readonly ValkeyValue Group = "GROUP";

    internal static readonly ValkeyValue Groups = "GROUPS";

    internal static readonly ValkeyValue JustId = "JUSTID";

    internal static readonly ValkeyValue SetId = "SETID";

    internal static readonly ValkeyValue MaxLen = "MAXLEN";

    internal static readonly ValkeyValue MkStream = "MKSTREAM";

    internal static readonly ValkeyValue NoAck = "NOACK";

    internal static readonly ValkeyValue Stream = "STREAM";

    internal static readonly ValkeyValue Streams = "STREAMS";
}
