# Project task-runner for glide-rust.
# Run commands by calling `cargo xtask <command> <args>`.
# See https://github.com/matklad/cargo-xtask for more details.
[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
