[package]
name = "mock-glide-core"
version = "0.1.0"
edition = "2024"

[dependencies]

# Mock crates for testing
glide-telemetry = { path = "../mock-glide-telemetry", package = "mock-glide-telemetry" }

# GLIDE dependencies
# TODO #6905: Update once renamed.
glide-core = { path = "../../../glide-core", features = ["proto"] }
redis = { path = "../mock-redis", package = "mock-redis" }

# External dependencies
protobuf = { version = "3", features = [] }
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread", "time"] }
