excludes:
  paths:
    - pattern: "benchmarks/csharp/**"
      reason: "TEST_OF"
      comment: Licenses contained in this directory are used for benchmarks and do not apply to the OSS Review Toolkit.
    - pattern: "csharp/tests/**"
      reason: "TEST_OF"
      comment: Licenses contained in this directory are used for testing and do not apply to the OSS Review Toolkit.
  scopes:
    - pattern: "xunit.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: Packages for testing only. Not part of released artifacts.
