# cargo-deny configuration.
# Run with `cargo deny check`.

[advisories]

# Advisory database location and source (RustSec).
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# Fail on crates yanked from their registry.
yanked = "deny"

[licenses]

# List of explicitly allowed licenses.
# See https://spdx.org/licenses/ for list of possible licenses.
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
    "MPL-2.0",
    "Zlib",
]

# The confidence threshold for detecting a license.
confidence-threshold = 0.8

# Per-crate license exceptions
exceptions = [
    { allow = ["CDLA-Permissive-2.0"], name = "webpki-root-certs", version = "*" },
]

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification entry for it allows you to manually specify the
# licensing information
[[licenses.clarify]]

# ring has no machine-readable license.
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"

# Each entry is a crate relative path, and the (opaque) hash of its contents
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]

# Check unpublished workspace crates.
ignore = false

[bans]

# Lint level for when multiple versions of the same crate are detected
multiple-versions = "allow"

# TODO #6519: Update once dependencies are published to crates.io.
# Our internal path deps (e.g. glide-core) don't specify a version, so their
# requirement resolves to a wildcard ('*').
wildcards = "allow"

# When duplicate versions exist, highlight all dependency paths to them.
highlight = "all"

[sources]

# Deny crates from unknown registries or git repositories.
unknown-registry = "deny"
unknown-git = "deny"
