/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class glide_ffi_resolvers_RedisValueResolver */

#ifndef _Included_glide_ffi_resolvers_RedisValueResolver
#define _Included_glide_ffi_resolvers_RedisValueResolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     glide_ffi_resolvers_RedisValueResolver
 * Method:    valueFromPointer
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_glide_ffi_resolvers_RedisValueResolver_valueFromPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
