/** Copyright Valkey GLIDE Project Contributors - SPDX Identifier: Apache-2.0 */
package glide.managers;

/**
 * Temporary copy of CommandType for compilation.
 * This should be replaced with proper module dependency to java-jni module.
 */
public enum CommandType {
    // String commands
    GET, SET, APPEND, DECR, DECRBY, GETDEL, GETEX, GETRANGE, 
    INCR, INCRBY, INCRBYFLOAT, LCS, MGET, MSET, MSETNX, SETRANGE, STRLEN,
    
    // Hash commands
    HDEL, HEXISTS, HGET, HGETALL, HINCRBY, HINCRBYFLOAT, HKEYS, HLEN,
    HMGET, HRANDFIELD, HSCAN, HSET, HSETNX, HSTRLEN, HVALS,
    
    // List commands
    BLMOVE, BLPOP, BRPOP, LINDEX, LINSERT, LLEN, LMOVE, LPOP, LPOS,
    LPUSH, LPUSHX, LRANGE, LREM, LSET, LTRIM, RPOP, RPUSH, RPUSHX,
    
    // Set commands
    SADD, SCARD, SDIFF, SDIFFSTORE, SINTER, SINTERSTORE, SISMEMBER,
    SMEMBERS, SMOVE, SPOP, SRANDMEMBER, SREM, SUNION, SUNIONSTORE,
    
    // Sorted Set commands
    BZPOPMAX, BZPOPMIN, ZADD, ZCARD, ZCOUNT, ZDIFF, ZDIFFSTORE,
    ZINCRBY, ZINTER, ZINTERSTORE, ZLEXCOUNT, ZMSCORE, ZPOPMAX, ZPOPMIN,
    ZRANDMEMBER, ZRANGE, ZRANGEBYLEX, ZRANGEBYSCORE, ZRANK, ZREM,
    ZREMRANGEBYLEX, ZREMRANGEBYRANK, ZREMRANGEBYSCORE, ZREVRANGE,
    ZREVRANGEBYLEX, ZREVRANGEBYSCORE, ZREVRANK, ZSCORE, ZUNION, ZUNIONSTORE,
    
    // Generic commands
    DEL, EXISTS, EXPIRE, EXPIREAT, EXPIRETIME, KEYS, MOVE, PERSIST,
    PEXPIRE, PEXPIREAT, PEXPIRETIME, PTTL, RANDOMKEY, RENAME, RENAMENX,
    TOUCH, TTL, TYPE, UNLINK,
    
    // Connection commands
    ECHO, PING, SELECT
}
