apiVersion: v1
kind: ConfigMap
metadata:
  name: glide-repro-config
  namespace: glide-repro
data:
  CLUSTER_ENDPOINT: "clustercfg.testing-cluster.ey5v7d.use2.cache.amazonaws.com"
  CLUSTER_PORT: "6379"
  NUM_THREADS: "60"
  MODE: "sync"
  VALUE_SIZE: "1024"
  REQUEST_TIMEOUT_MS: "1000"
  JAVA_TIMEOUT_MS: "1050"
  JAVA_TIMEOUT_STYLE: "complete_future"
  USE_TLS: "true"
  KEYS_PER_DEL: "6"
  HASH_TAG_MODE: "none"
  KEY_SPACE: "10000000"
  HEARTBEAT_DIR: "/shared/heartbeats"
  RESULTS_DIR: "/shared/results"
  GLIDE_TOKIO_WORKER_THREADS: "1"
