name: Install Rust toolchain
description: Install a Rust toolchain with rustfmt and clippy

inputs:
    toolchain:
        description: "Rust toolchain to install (e.g. '1.88.0')"
        required: false
        default: "stable"
    target:
        description: "Build target (e.g. 'x86_64-unknown-linux-gnu')"
        required: false
        default: "x86_64-unknown-linux-gnu"

runs:
    using: "composite"
    steps:
        - name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
          with:
              toolchain: ${{ inputs.toolchain }}
              targets: ${{ inputs.target }}
              components: rustfmt, clippy
