name: Install zig compiler and ziglang

inputs:
    target:
        description: "Specified target for rust toolchain, ex. x86_64-unknown-linux-gnu"
        type: string
        required: false
        default: "x86_64-unknown-linux-gnu"

runs:
    using: "composite"
    steps:
        - name: Install zig
          shell: bash
          run: |
              if [[ `cat /etc/os-release | grep "Amazon Linux"` ]]; then
                  yum install -y python3-pip
              else
                  sudo apt install -y python3-pip
              fi
              pip3 install ziglang
              cargo install --locked cargo-zigbuild
              
              # Set environment variables to prevent cargo-zigbuild from auto-detecting malformed targets
              # These will be available for subsequent steps in the workflow
              echo "CARGO_BUILD_TARGET=${{ inputs.target }}" >> $GITHUB_ENV
              echo "CARGO_ZIGBUILD_TARGET=${{ inputs.target }}" >> $GITHUB_ENV
