name: Task
description: Create a task to manage work
title: "[Task]"
labels: ["task"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              ## Task Description

    - type: textarea
      attributes:
          label: Description
          description: Describe the task in detail
          placeholder: Describe the task...

    - type: textarea
      attributes:
          label: Checklist
          description: Add items to be completed
          value: |
              1. 
              2. 
              ...

    - type: textarea
      attributes:
          label: Additional Notes
          description: Add any additional notes or comments
          placeholder: Any additional notes...
