name: "Setup Windows Dependencies"
description: "Setup Python, SSH, and other Windows-specific dependencies"

inputs:
    github-token:
        description: "GitHub token for authentication"
        required: false
        default: ${{ github.token }}

outputs:
    python-available:
        description: "Whether Python is available"
        value: ${{ steps.check.outputs.python-available }}
    ssh-available:
        description: "Whether SSH is available"
        value: ${{ steps.check.outputs.ssh-available }}

runs:
    using: "composite"
    steps:
        - name: Check Windows dependencies
          id: check
          shell: powershell
          run: |
              Write-Host "Checking Windows dependencies..."

              # Debug: Show current PATH
              Write-Host "Current PATH:"
              $env:PATH -split ';' | ForEach-Object { Write-Host "  $_" }

              # Debug: Show all executables that might be Python
              Write-Host "All python-like executables in PATH:"
              Get-Command python*, py -ErrorAction SilentlyContinue | ForEach-Object { 
                  Write-Host "  $($_.Name) -> $($_.Source)"
                  try {
                      $version = & $_.Source --version 2>&1
                      Write-Host "    Version: $version"
                  } catch {
                      Write-Host "    Version check failed: $_"
                  }
              }

              # Check for Python installations
              $pythonAvailable = $false
              $pythonPath = $null

              # Method 1: Check PATH commands
              Write-Host "Method 1: Checking PATH commands..."
              if (Get-Command python3 -ErrorAction SilentlyContinue) {
                  $pythonAvailable = $true
                  $pythonPath = (Get-Command python3).Source
                  Write-Host "Found python3 in PATH: $pythonPath"
              } elseif (Get-Command python -ErrorAction SilentlyContinue) {
                  $version = python --version 2>&1
                  Write-Host "Found python command, version: $version"
                  if ($version -match "Python 3\.") {
                      $pythonAvailable = $true
                      $pythonPath = (Get-Command python).Source
                      Write-Host "Found Python 3.x via python command: $version"
                  } else {
                      Write-Host "Python found but not version 3.x: $version"
                  }
              } elseif (Get-Command py -ErrorAction SilentlyContinue) {
                  Write-Host "Found py launcher, checking version..."
                  try {
                      $version = py --version 2>&1
                      Write-Host "py launcher version: $version"
                      if ($version -match "Python 3\.") {
                          $pythonAvailable = $true
                          $pythonPath = (Get-Command py).Source
                          Write-Host "Found Python 3.x via py launcher: $version"
                      }
                  } catch {
                      Write-Host "py launcher version check failed: $_"
                  }
              } else {
                  Write-Host "No python commands found in PATH"
              }

              # Method 2: Check registry if not found in PATH
              if (-not $pythonAvailable) {
                  Write-Host "Method 2: Checking Windows registry for Python..."
                  $regPaths = @(
                      "HKLM:\SOFTWARE\Python\PythonCore\*\InstallPath",
                      "HKCU:\SOFTWARE\Python\PythonCore\*\InstallPath",
                      "HKLM:\SOFTWARE\WOW6432Node\Python\PythonCore\*\InstallPath"
                  )

                  foreach ($regPath in $regPaths) {
                      Write-Host "Checking registry path: $regPath"
                      try {
                          Get-ItemProperty $regPath -ErrorAction SilentlyContinue | ForEach-Object {
                              $installPath = $_.'(default)'
                              Write-Host "Registry entry found: $installPath"
                              if ($installPath -and (Test-Path $installPath)) {
                                  $pythonExe = Join-Path $installPath "python.exe"
                                  Write-Host "Checking: $pythonExe"
                                  if (Test-Path $pythonExe) {
                                      try {
                                          $version = & $pythonExe --version 2>&1
                                          Write-Host "Found Python at $pythonExe - Version: $version"
                                          if ($version -match "Python 3\.") {
                                              $pythonAvailable = $true
                                              $pythonPath = $pythonExe
                                              Write-Host "Using Python 3.x from registry: $pythonExe"
                                              break
                                          }
                                      } catch {
                                          Write-Host "Version check failed for $pythonExe : $_"
                                      }
                                  } else {
                                      Write-Host "python.exe not found at: $pythonExe"
                                  }
                              } else {
                                  Write-Host "Install path does not exist: $installPath"
                              }
                          }
                      } catch {
                          Write-Host "Registry check failed for $regPath : $_"
                      }
                      if ($pythonAvailable) { break }
                  }
              }

              # Method 3: Check common paths if still not found
              if (-not $pythonAvailable) {
                  Write-Host "Method 3: Checking common installation paths..."
                  $commonPaths = @(
                      "$env:LOCALAPPDATA\Programs\Python\Python*",
                      "$env:PROGRAMFILES\Python*",
                      "$env:PROGRAMFILES(x86)\Python*",
                      "C:\Python*"
                  )

                  foreach ($pathPattern in $commonPaths) {
                      Write-Host "Checking pattern: $pathPattern"
                      Get-ChildItem $pathPattern -Directory -ErrorAction SilentlyContinue | ForEach-Object {
                          $pythonExe = Join-Path $_.FullName "python.exe"
                          Write-Host "Checking: $pythonExe"
                          if (Test-Path $pythonExe) {
                              try {
                                  $version = & $pythonExe --version 2>&1
                                  Write-Host "Found Python at $pythonExe - Version: $version"
                                  if ($version -match "Python 3\.") {
                                      $pythonAvailable = $true
                                      $pythonPath = $pythonExe
                                      Write-Host "Using Python 3.x from common path: $pythonExe"
                                      break
                                  }
                              } catch {
                                  Write-Host "Version check failed for $pythonExe : $_"
                              }
                          } else {
                              Write-Host "python.exe not found at: $pythonExe"
                          }
                      }
                      if ($pythonAvailable) { break }
                  }
              }

              # Check SSH
              $sshAvailable = $false
              if (Get-Command ssh -ErrorAction SilentlyContinue) {
                  $sshAvailable = $true
                  Write-Host "SSH client available"
              } else {
                  Write-Host "SSH client not found"
              }

              # Set outputs
              echo "python-available=$pythonAvailable" >> $env:GITHUB_OUTPUT
              echo "ssh-available=$sshAvailable" >> $env:GITHUB_OUTPUT

              Write-Host "Detection complete: Python=$pythonAvailable, SSH=$sshAvailable"

        - name: Install Visual Studio Build Tools
          shell: powershell
          env:
              GITHUB_TOKEN: ${{ inputs.github-token }}
          run: |
              # Check if Visual Studio Build Tools are already installed
              $vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
              if (Test-Path $vsWhere) {
                  $buildTools = & $vsWhere -products Microsoft.VisualStudio.Product.BuildTools -format json | ConvertFrom-Json
                  if ($buildTools) {
                      Write-Host "Visual Studio Build Tools already installed"
                      return
                  }
              }

              Write-Host "Installing Visual Studio Build Tools..."

              # Download Visual Studio Build Tools installer
              $installerUrl = "https://aka.ms/vs/17/release/vs_buildtools.exe"
              $installerPath = "$env:TEMP\vs_buildtools.exe"

              # Add authentication header if token is available
              $headers = @{}
              if ($env:GITHUB_TOKEN) {
                  $headers["Authorization"] = "Bearer $env:GITHUB_TOKEN"
              }

              try {
                  if ($headers.Count -gt 0) {
                      Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath -Headers $headers
                  } else {
                      Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
                  }
              } catch {
                  Write-Host "Failed to download with authentication, trying without: $_"
                  Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
              }

              # Install with C++ build tools
              Write-Host "Installing C++ build tools..."
              & $installerPath --quiet --wait --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041

              Write-Host "Visual Studio Build Tools installation complete"

        - name: Verify and setup MSVC environment
          shell: powershell
          run: |
              Write-Host "Verifying MSVC installation..."
              
              # Find Visual Studio installation
              $vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
              if (Test-Path $vsWhere) {
                  $vsInstallation = & $vsWhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
                  if ($vsInstallation) {
                      Write-Host "Found Visual Studio installation at: $vsInstallation"
                      
                      # Add MSVC tools to PATH
                      $vcToolsPath = "$vsInstallation\VC\Tools\MSVC"
                      if (Test-Path $vcToolsPath) {
                          $latestMSVC = Get-ChildItem $vcToolsPath | Sort-Object Name -Descending | Select-Object -First 1
                          if ($latestMSVC) {
                              $msvcBinPath = "$($latestMSVC.FullName)\bin\Hostx64\x64"
                              if (Test-Path $msvcBinPath) {
                                  $env:PATH = "$msvcBinPath;$env:PATH"
                                  echo "PATH=$env:PATH" >> $env:GITHUB_ENV
                                  Write-Host "Added MSVC tools to PATH: $msvcBinPath"
                              }
                          }
                      }
                  }
              }
              
              # Verify link.exe is available
              try {
                  $linkPath = Get-Command link.exe -ErrorAction Stop
                  Write-Host "✓ link.exe found at: $($linkPath.Source)"
              } catch {
                  Write-Host "✗ link.exe not found in PATH"
                  Write-Host "This will cause Rust compilation to fail"
              }

        - name: Setup Python3 symlink
          if: steps.check.outputs.python-available == 'true'
          shell: powershell
          run: |
              if (-not (Get-Command python3 -ErrorAction SilentlyContinue)) {
                  if (Get-Command python -ErrorAction SilentlyContinue) {
                      Write-Host "Creating python3 symlink..."
                      $pythonPath = (Get-Command python).Source
                      $python3Path = Join-Path (Split-Path $pythonPath) "python3.exe"
                      New-Item -ItemType HardLink -Path $python3Path -Target $pythonPath -Force
                      Write-Host "python3 symlink created"
                  }
              } else {
                  Write-Host "python3 command already exists"
              }

        - name: Install Python (when missing)
          if: steps.check.outputs.python-available != 'true'
          shell: powershell
          run: |
              Write-Host "Installing Python 3.11..."

              # Download Python installer
              $pythonUrl = "https://www.python.org/ftp/python/3.11.7/python-3.11.7-amd64.exe"
              $installerPath = "$env:TEMP\python-installer.exe"

              Write-Host "Downloading Python installer..."
              Invoke-WebRequest -Uri $pythonUrl -OutFile $installerPath

              Write-Host "Installing Python (current user only)..."
              # Install for current user only, add to PATH
              Start-Process -FilePath $installerPath -ArgumentList "/quiet", "InstallAllUsers=0", "PrependPath=1", "Include_test=0" -Wait

              Write-Host "Cleaning up installer..."
              Remove-Item $installerPath -Force

              Write-Host "Locating installed Python..."
              # Check common installation locations for current user
              $pythonPaths = @(
                  "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe",
                  "$env:LOCALAPPDATA\Programs\Python\Python311-32\python.exe",
                  "$env:APPDATA\Local\Programs\Python\Python311\python.exe"
              )

              $foundPython = $null
              foreach ($path in $pythonPaths) {
                  if (Test-Path $path) {
                      $foundPython = $path
                      Write-Host "Found Python at: $path"
                      break
                  }
              }

              if ($foundPython) {
                  # Add Python directory to current session PATH
                  $pythonDir = Split-Path $foundPython
                  $scriptsDir = Join-Path $pythonDir "Scripts"
                  $env:PATH = "$pythonDir;$scriptsDir;$env:PATH"
                  Write-Host "Added to PATH: $pythonDir"
                  Write-Host "Added to PATH: $scriptsDir"

                  # Verify installation
                  try {
                      $version = & $foundPython --version 2>&1
                      Write-Host "Python installed successfully: $version"
                  } catch {
                      Write-Host "Python installation verification failed: $_"
                  }
              } else {
                  Write-Host "Python installation may have failed - executable not found"
              }

              Write-Host "Python installation complete"

        - name: Verify Python setup
          shell: powershell
          run: |
              Write-Host "Verifying Python setup..."

              $pythonWorking = $false

              if (Get-Command python3 -ErrorAction SilentlyContinue) {
                  try {
                      $version = python3 --version 2>&1
                      Write-Host "Python3 ready: $version"
                      $pythonWorking = $true
                  } catch {
                      Write-Host "Python3 command failed: $_"
                  }
              } elseif (Get-Command python -ErrorAction SilentlyContinue) {
                  try {
                      $version = python --version 2>&1
                      Write-Host "Python ready: $version"
                      $pythonWorking = $true
                  } catch {
                      Write-Host "Python command failed: $_"
                  }
              } else {
                  Write-Host "No Python commands available"
              }

              if (-not $pythonWorking) {
                  Write-Host "Warning: Python verification failed, but continuing workflow"
                  Write-Host "Python may still work for the actual build process"
              } else {
                  Write-Host "Python verification successful"
              }
