#!/bin/bash -e
npm install --save-dev typedoc
typedoc src/BaseClient.ts                   \
        src/Batch.ts                  \
        src/GlideClient.ts                  \
        src/GlideClusterClient.ts           \
        src/Errors.ts                       \
        src/Commands.ts                     \
        src/Logger.ts                       \
        src/server-modules/GlideFt.ts       \
        src/server-modules/FtOptions.ts     \
        src/server-modules/GlideJson.ts     \
        --plugin typedoc-plugin-markdown    \
        --disableSources                    \
        --includeHierarchySummary           \
        --out ../docs/markdown/node/


# Run urls conversion script - makes them apear not broken in the website
node ./docs/convert-urls.mjs
