name: Cleanup Valkey/Redis WSL on Windows
description: Stops and removes Valkey/Redis containers from WSL

inputs:
    port-prefix:
        description: "Port prefix used during setup"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - name: Cleanup WSL containers
          shell: pwsh
          env:
              PORT_PREFIX: ${{ inputs.port-prefix }}
          run: |
              Write-Host "Cleaning up Valkey/Redis in WSL..."

              $PORT_PREFIX = $env:PORT_PREFIX
              $STANDALONE_PORT = "${PORT_PREFIX}6379"
              $CLUSTER_PORTS = @("${PORT_PREFIX}7000", "${PORT_PREFIX}7001", "${PORT_PREFIX}7002")

              # Stop and remove all containers
              Write-Host "Stopping containers..."
              wsl sudo docker stop valkey-standalone 2>`$null
              wsl sudo docker rm valkey-standalone 2>`$null

              foreach ($port in $CLUSTER_PORTS) {
                  wsl sudo docker stop valkey-cluster-$port 2>`$null
                  wsl sudo docker rm valkey-cluster-$port 2>`$null
              }

              # Remove network
              wsl sudo docker network rm valkey-net 2>`$null

              Write-Host "✓ WSL cleanup complete"
