name: Cleanup Valkey/Redis WSL on Windows
description: Stops and removes Valkey/Redis containers from WSL

inputs:
    port-prefix:
        description: "Port prefix used during setup"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - name: Cleanup WSL containers
          shell: pwsh
          env:
              PORT_PREFIX: ${{ inputs.port-prefix }}
          run: |
              Write-Host "Cleaning up Valkey/Redis in WSL..."

              # Check if WSL has Ubuntu installed
              $wslList = wsl --list --quiet 2>$null
              if ($wslList -notcontains "Ubuntu-22.04") {
                  Write-Host "Ubuntu-22.04 not found, skipping cleanup"
                  exit 0
              }

              $PORT_PREFIX = $env:PORT_PREFIX
              $STANDALONE_PORT = "${PORT_PREFIX}6379"
              $CLUSTER_PORTS = @("${PORT_PREFIX}7000", "${PORT_PREFIX}7001", "${PORT_PREFIX}7002")

              # Stop and remove all containers
              Write-Host "Stopping containers..."
              wsl -d Ubuntu-22.04 sudo docker stop valkey-standalone 2>`$null
              wsl -d Ubuntu-22.04 sudo docker rm valkey-standalone 2>`$null

              foreach ($port in $CLUSTER_PORTS) {
                  wsl -d Ubuntu-22.04 sudo docker stop valkey-cluster-$port 2>`$null
                  wsl -d Ubuntu-22.04 sudo docker rm valkey-cluster-$port 2>`$null
              }

              # Remove network
              wsl -d Ubuntu-22.04 sudo docker network rm valkey-net 2>`$null

              Write-Host "✓ WSL cleanup complete"
