name: Install Redis Modules

inputs:
    redis-version:
        description: "redis version of clusters"
        required: true
        type: string
    
    modules:
      description: "required redis modules to install"
      required: false
      type: string
      default: 'all'
      options:
        - "all"
        - "search"
        - "json"



runs:
    using: "composite"
    steps:
        - name: Cache RedisJSON Dependencies
          if: inputs.modules == 'all' || inputs.modules == 'json'
          id: cache-dependencies-redisjson
          uses: actions/cache@v3
          with:
            path: |
              ./cmake
              ./redisjson/bin 
            key: ${{ runner.os }}-${{ inputs.redis-version }}-redisjson

        
        - name: Install CMake
          if: steps.cache-dependencies-redisearch.outputs.cache-hit != 'true' || steps.cache-dependencies-redisjson.outputs.cache-hit != 'true'
          shell: bash  
          run: |
            set -x
            sudo apt-get update
            sudo apt-get install -y cmake
            cp /usr/bin/cmake ./cmake
          

        - name: Checkout RedisJSON Repository
          if: steps.cache-dependencies-redisjson.outputs.cache-hit != 'true' && (inputs.modules == 'all' || inputs.modules == 'json')
          uses: actions/checkout@v4
          with: 
              repository: "RedisJSON/RedisJSON"
              path: "./redisjson" 
              ref: ${{ startsWith(inputs.redis-version, '6') && 'v2.6.0' || '' }}
              submodules: recursive

        - name: Build RedisJSON
          if: steps.cache-dependencies-redisjson.outputs.cache-hit != 'true' && (inputs.modules == 'all' || inputs.modules == 'json')
          shell: bash 
          working-directory: ./redisjson
          run: |
            set -x
            echo "Building RedisJSON..."
            make
        
        - name: Copy redisjson.so
          if: inputs.modules == 'all' || inputs.modules == 'json'
          shell: bash  
          run: |
            set -x
            echo "Copying RedisJSON..."
            cp $GITHUB_WORKSPACE/redisjson/bin/linux-x64-release/rejson.so $GITHUB_WORKSPACE/redisjson.so
