[package]
name = "mock-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { path = "../../../glide-core/redis-rs/redis", features = ["aio", "tokio-comp", "tokio-rustls-comp"] }
telemetrylib = { path = "../mock-telemetry", package = "mock-telemetry" }
