// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/response.proto
// Protobuf Java Version: 4.29.1

package response;

public final class ResponseOuterClass {
  private ResponseOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      ResponseOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code response.RequestErrorType}
   */
  public enum RequestErrorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unspecified = 0;</code>
     */
    Unspecified(0),
    /**
     * <code>ExecAbort = 1;</code>
     */
    ExecAbort(1),
    /**
     * <code>Timeout = 2;</code>
     */
    Timeout(2),
    /**
     * <code>Disconnect = 3;</code>
     */
    Disconnect(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        RequestErrorType.class.getName());
    }
    /**
     * <code>Unspecified = 0;</code>
     */
    public static final int Unspecified_VALUE = 0;
    /**
     * <code>ExecAbort = 1;</code>
     */
    public static final int ExecAbort_VALUE = 1;
    /**
     * <code>Timeout = 2;</code>
     */
    public static final int Timeout_VALUE = 2;
    /**
     * <code>Disconnect = 3;</code>
     */
    public static final int Disconnect_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestErrorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestErrorType forNumber(int value) {
      switch (value) {
        case 0: return Unspecified;
        case 1: return ExecAbort;
        case 2: return Timeout;
        case 3: return Disconnect;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestErrorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestErrorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestErrorType>() {
            public RequestErrorType findValueByNumber(int number) {
              return RequestErrorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return response.ResponseOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestErrorType[] VALUES = values();

    public static RequestErrorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestErrorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:response.RequestErrorType)
  }

  /**
   * Protobuf enum {@code response.ConstantResponse}
   */
  public enum ConstantResponse
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        ConstantResponse.class.getName());
    }
    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConstantResponse valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ConstantResponse forNumber(int value) {
      switch (value) {
        case 0: return OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConstantResponse>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConstantResponse> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConstantResponse>() {
            public ConstantResponse findValueByNumber(int number) {
              return ConstantResponse.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return response.ResponseOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final ConstantResponse[] VALUES = values();

    public static ConstantResponse valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConstantResponse(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:response.ConstantResponse)
  }

  public interface RequestErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response.RequestError)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.response.RequestErrorType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.response.RequestErrorType type = 1;</code>
     * @return The type.
     */
    response.ResponseOuterClass.RequestErrorType getType();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code response.RequestError}
   */
  public static final class RequestError extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:response.RequestError)
      RequestErrorOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        RequestError.class.getName());
    }
    // Use RequestError.newBuilder() to construct.
    private RequestError(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestError() {
      type_ = 0;
      message_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return response.ResponseOuterClass.internal_static_response_RequestError_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return response.ResponseOuterClass.internal_static_response_RequestError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              response.ResponseOuterClass.RequestError.class, response.ResponseOuterClass.RequestError.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.response.RequestErrorType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.response.RequestErrorType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public response.ResponseOuterClass.RequestErrorType getType() {
      response.ResponseOuterClass.RequestErrorType result = response.ResponseOuterClass.RequestErrorType.forNumber(type_);
      return result == null ? response.ResponseOuterClass.RequestErrorType.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != response.ResponseOuterClass.RequestErrorType.Unspecified.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != response.ResponseOuterClass.RequestErrorType.Unspecified.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof response.ResponseOuterClass.RequestError)) {
        return super.equals(obj);
      }
      response.ResponseOuterClass.RequestError other = (response.ResponseOuterClass.RequestError) obj;

      if (type_ != other.type_) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static response.ResponseOuterClass.RequestError parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static response.ResponseOuterClass.RequestError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static response.ResponseOuterClass.RequestError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static response.ResponseOuterClass.RequestError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(response.ResponseOuterClass.RequestError prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code response.RequestError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response.RequestError)
        response.ResponseOuterClass.RequestErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return response.ResponseOuterClass.internal_static_response_RequestError_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return response.ResponseOuterClass.internal_static_response_RequestError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                response.ResponseOuterClass.RequestError.class, response.ResponseOuterClass.RequestError.Builder.class);
      }

      // Construct using response.ResponseOuterClass.RequestError.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return response.ResponseOuterClass.internal_static_response_RequestError_descriptor;
      }

      @java.lang.Override
      public response.ResponseOuterClass.RequestError getDefaultInstanceForType() {
        return response.ResponseOuterClass.RequestError.getDefaultInstance();
      }

      @java.lang.Override
      public response.ResponseOuterClass.RequestError build() {
        response.ResponseOuterClass.RequestError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public response.ResponseOuterClass.RequestError buildPartial() {
        response.ResponseOuterClass.RequestError result = new response.ResponseOuterClass.RequestError(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(response.ResponseOuterClass.RequestError result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof response.ResponseOuterClass.RequestError) {
          return mergeFrom((response.ResponseOuterClass.RequestError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(response.ResponseOuterClass.RequestError other) {
        if (other == response.ResponseOuterClass.RequestError.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.response.RequestErrorType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.response.RequestErrorType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.response.RequestErrorType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public response.ResponseOuterClass.RequestErrorType getType() {
        response.ResponseOuterClass.RequestErrorType result = response.ResponseOuterClass.RequestErrorType.forNumber(type_);
        return result == null ? response.ResponseOuterClass.RequestErrorType.UNRECOGNIZED : result;
      }
      /**
       * <code>.response.RequestErrorType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(response.ResponseOuterClass.RequestErrorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.response.RequestErrorType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:response.RequestError)
    }

    // @@protoc_insertion_point(class_scope:response.RequestError)
    private static final response.ResponseOuterClass.RequestError DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new response.ResponseOuterClass.RequestError();
    }

    public static response.ResponseOuterClass.RequestError getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestError>
        PARSER = new com.google.protobuf.AbstractParser<RequestError>() {
      @java.lang.Override
      public RequestError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RequestError> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestError> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public response.ResponseOuterClass.RequestError getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 callback_idx = 1;</code>
     * @return The callbackIdx.
     */
    int getCallbackIdx();

    /**
     * <code>uint64 resp_pointer = 2;</code>
     * @return Whether the respPointer field is set.
     */
    boolean hasRespPointer();
    /**
     * <code>uint64 resp_pointer = 2;</code>
     * @return The respPointer.
     */
    long getRespPointer();

    /**
     * <code>.response.ConstantResponse constant_response = 3;</code>
     * @return Whether the constantResponse field is set.
     */
    boolean hasConstantResponse();
    /**
     * <code>.response.ConstantResponse constant_response = 3;</code>
     * @return The enum numeric value on the wire for constantResponse.
     */
    int getConstantResponseValue();
    /**
     * <code>.response.ConstantResponse constant_response = 3;</code>
     * @return The constantResponse.
     */
    response.ResponseOuterClass.ConstantResponse getConstantResponse();

    /**
     * <code>.response.RequestError request_error = 4;</code>
     * @return Whether the requestError field is set.
     */
    boolean hasRequestError();
    /**
     * <code>.response.RequestError request_error = 4;</code>
     * @return The requestError.
     */
    response.ResponseOuterClass.RequestError getRequestError();
    /**
     * <code>.response.RequestError request_error = 4;</code>
     */
    response.ResponseOuterClass.RequestErrorOrBuilder getRequestErrorOrBuilder();

    /**
     * <code>string closing_error = 5;</code>
     * @return Whether the closingError field is set.
     */
    boolean hasClosingError();
    /**
     * <code>string closing_error = 5;</code>
     * @return The closingError.
     */
    java.lang.String getClosingError();
    /**
     * <code>string closing_error = 5;</code>
     * @return The bytes for closingError.
     */
    com.google.protobuf.ByteString
        getClosingErrorBytes();

    /**
     * <code>bool is_push = 6;</code>
     * @return The isPush.
     */
    boolean getIsPush();

    /**
     * <code>optional uint64 root_span_ptr = 7;</code>
     * @return Whether the rootSpanPtr field is set.
     */
    boolean hasRootSpanPtr();
    /**
     * <code>optional uint64 root_span_ptr = 7;</code>
     * @return The rootSpanPtr.
     */
    long getRootSpanPtr();

    response.ResponseOuterClass.Response.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code response.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:response.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Response.class.getName());
    }
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Response() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return response.ResponseOuterClass.internal_static_response_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return response.ResponseOuterClass.internal_static_response_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              response.ResponseOuterClass.Response.class, response.ResponseOuterClass.Response.Builder.class);
    }

    private int bitField0_;
    private int valueCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      RESP_POINTER(2),
      CONSTANT_RESPONSE(3),
      REQUEST_ERROR(4),
      CLOSING_ERROR(5),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 2: return RESP_POINTER;
          case 3: return CONSTANT_RESPONSE;
          case 4: return REQUEST_ERROR;
          case 5: return CLOSING_ERROR;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int CALLBACK_IDX_FIELD_NUMBER = 1;
    private int callbackIdx_ = 0;
    /**
     * <code>uint32 callback_idx = 1;</code>
     * @return The callbackIdx.
     */
    @java.lang.Override
    public int getCallbackIdx() {
      return callbackIdx_;
    }

    public static final int RESP_POINTER_FIELD_NUMBER = 2;
    /**
     * <code>uint64 resp_pointer = 2;</code>
     * @return Whether the respPointer field is set.
     */
    @java.lang.Override
    public boolean hasRespPointer() {
      return valueCase_ == 2;
    }
    /**
     * <code>uint64 resp_pointer = 2;</code>
     * @return The respPointer.
     */
    @java.lang.Override
    public long getRespPointer() {
      if (valueCase_ == 2) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }

    public static final int CONSTANT_RESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>.response.ConstantResponse constant_response = 3;</code>
     * @return Whether the constantResponse field is set.
     */
    public boolean hasConstantResponse() {
      return valueCase_ == 3;
    }
    /**
     * <code>.response.ConstantResponse constant_response = 3;</code>
     * @return The enum numeric value on the wire for constantResponse.
     */
    public int getConstantResponseValue() {
      if (valueCase_ == 3) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <code>.response.ConstantResponse constant_response = 3;</code>
     * @return The constantResponse.
     */
    public response.ResponseOuterClass.ConstantResponse getConstantResponse() {
      if (valueCase_ == 3) {
        response.ResponseOuterClass.ConstantResponse result = response.ResponseOuterClass.ConstantResponse.forNumber(
            (java.lang.Integer) value_);
        return result == null ? response.ResponseOuterClass.ConstantResponse.UNRECOGNIZED : result;
      }
      return response.ResponseOuterClass.ConstantResponse.OK;
    }

    public static final int REQUEST_ERROR_FIELD_NUMBER = 4;
    /**
     * <code>.response.RequestError request_error = 4;</code>
     * @return Whether the requestError field is set.
     */
    @java.lang.Override
    public boolean hasRequestError() {
      return valueCase_ == 4;
    }
    /**
     * <code>.response.RequestError request_error = 4;</code>
     * @return The requestError.
     */
    @java.lang.Override
    public response.ResponseOuterClass.RequestError getRequestError() {
      if (valueCase_ == 4) {
         return (response.ResponseOuterClass.RequestError) value_;
      }
      return response.ResponseOuterClass.RequestError.getDefaultInstance();
    }
    /**
     * <code>.response.RequestError request_error = 4;</code>
     */
    @java.lang.Override
    public response.ResponseOuterClass.RequestErrorOrBuilder getRequestErrorOrBuilder() {
      if (valueCase_ == 4) {
         return (response.ResponseOuterClass.RequestError) value_;
      }
      return response.ResponseOuterClass.RequestError.getDefaultInstance();
    }

    public static final int CLOSING_ERROR_FIELD_NUMBER = 5;
    /**
     * <code>string closing_error = 5;</code>
     * @return Whether the closingError field is set.
     */
    public boolean hasClosingError() {
      return valueCase_ == 5;
    }
    /**
     * <code>string closing_error = 5;</code>
     * @return The closingError.
     */
    public java.lang.String getClosingError() {
      java.lang.Object ref = "";
      if (valueCase_ == 5) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 5) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string closing_error = 5;</code>
     * @return The bytes for closingError.
     */
    public com.google.protobuf.ByteString
        getClosingErrorBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 5) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 5) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_PUSH_FIELD_NUMBER = 6;
    private boolean isPush_ = false;
    /**
     * <code>bool is_push = 6;</code>
     * @return The isPush.
     */
    @java.lang.Override
    public boolean getIsPush() {
      return isPush_;
    }

    public static final int ROOT_SPAN_PTR_FIELD_NUMBER = 7;
    private long rootSpanPtr_ = 0L;
    /**
     * <code>optional uint64 root_span_ptr = 7;</code>
     * @return Whether the rootSpanPtr field is set.
     */
    @java.lang.Override
    public boolean hasRootSpanPtr() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 root_span_ptr = 7;</code>
     * @return The rootSpanPtr.
     */
    @java.lang.Override
    public long getRootSpanPtr() {
      return rootSpanPtr_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (callbackIdx_ != 0) {
        output.writeUInt32(1, callbackIdx_);
      }
      if (valueCase_ == 2) {
        output.writeUInt64(
            2, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 3) {
        output.writeEnum(3, ((java.lang.Integer) value_));
      }
      if (valueCase_ == 4) {
        output.writeMessage(4, (response.ResponseOuterClass.RequestError) value_);
      }
      if (valueCase_ == 5) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, value_);
      }
      if (isPush_ != false) {
        output.writeBool(6, isPush_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(7, rootSpanPtr_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (callbackIdx_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, callbackIdx_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(
              2, (long)((java.lang.Long) value_));
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, ((java.lang.Integer) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (response.ResponseOuterClass.RequestError) value_);
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, value_);
      }
      if (isPush_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isPush_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, rootSpanPtr_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof response.ResponseOuterClass.Response)) {
        return super.equals(obj);
      }
      response.ResponseOuterClass.Response other = (response.ResponseOuterClass.Response) obj;

      if (getCallbackIdx()
          != other.getCallbackIdx()) return false;
      if (getIsPush()
          != other.getIsPush()) return false;
      if (hasRootSpanPtr() != other.hasRootSpanPtr()) return false;
      if (hasRootSpanPtr()) {
        if (getRootSpanPtr()
            != other.getRootSpanPtr()) return false;
      }
      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 2:
          if (getRespPointer()
              != other.getRespPointer()) return false;
          break;
        case 3:
          if (getConstantResponseValue()
              != other.getConstantResponseValue()) return false;
          break;
        case 4:
          if (!getRequestError()
              .equals(other.getRequestError())) return false;
          break;
        case 5:
          if (!getClosingError()
              .equals(other.getClosingError())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CALLBACK_IDX_FIELD_NUMBER;
      hash = (53 * hash) + getCallbackIdx();
      hash = (37 * hash) + IS_PUSH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsPush());
      if (hasRootSpanPtr()) {
        hash = (37 * hash) + ROOT_SPAN_PTR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRootSpanPtr());
      }
      switch (valueCase_) {
        case 2:
          hash = (37 * hash) + RESP_POINTER_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getRespPointer());
          break;
        case 3:
          hash = (37 * hash) + CONSTANT_RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getConstantResponseValue();
          break;
        case 4:
          hash = (37 * hash) + REQUEST_ERROR_FIELD_NUMBER;
          hash = (53 * hash) + getRequestError().hashCode();
          break;
        case 5:
          hash = (37 * hash) + CLOSING_ERROR_FIELD_NUMBER;
          hash = (53 * hash) + getClosingError().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static response.ResponseOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static response.ResponseOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static response.ResponseOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static response.ResponseOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static response.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(response.ResponseOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code response.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response.Response)
        response.ResponseOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return response.ResponseOuterClass.internal_static_response_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return response.ResponseOuterClass.internal_static_response_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                response.ResponseOuterClass.Response.class, response.ResponseOuterClass.Response.Builder.class);
      }

      // Construct using response.ResponseOuterClass.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        callbackIdx_ = 0;
        if (requestErrorBuilder_ != null) {
          requestErrorBuilder_.clear();
        }
        isPush_ = false;
        rootSpanPtr_ = 0L;
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return response.ResponseOuterClass.internal_static_response_Response_descriptor;
      }

      @java.lang.Override
      public response.ResponseOuterClass.Response getDefaultInstanceForType() {
        return response.ResponseOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public response.ResponseOuterClass.Response build() {
        response.ResponseOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public response.ResponseOuterClass.Response buildPartial() {
        response.ResponseOuterClass.Response result = new response.ResponseOuterClass.Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(response.ResponseOuterClass.Response result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.callbackIdx_ = callbackIdx_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.isPush_ = isPush_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.rootSpanPtr_ = rootSpanPtr_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(response.ResponseOuterClass.Response result) {
        result.valueCase_ = valueCase_;
        result.value_ = this.value_;
        if (valueCase_ == 4 &&
            requestErrorBuilder_ != null) {
          result.value_ = requestErrorBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof response.ResponseOuterClass.Response) {
          return mergeFrom((response.ResponseOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(response.ResponseOuterClass.Response other) {
        if (other == response.ResponseOuterClass.Response.getDefaultInstance()) return this;
        if (other.getCallbackIdx() != 0) {
          setCallbackIdx(other.getCallbackIdx());
        }
        if (other.getIsPush() != false) {
          setIsPush(other.getIsPush());
        }
        if (other.hasRootSpanPtr()) {
          setRootSpanPtr(other.getRootSpanPtr());
        }
        switch (other.getValueCase()) {
          case RESP_POINTER: {
            setRespPointer(other.getRespPointer());
            break;
          }
          case CONSTANT_RESPONSE: {
            setConstantResponseValue(other.getConstantResponseValue());
            break;
          }
          case REQUEST_ERROR: {
            mergeRequestError(other.getRequestError());
            break;
          }
          case CLOSING_ERROR: {
            valueCase_ = 5;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                callbackIdx_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                value_ = input.readUInt64();
                valueCase_ = 2;
                break;
              } // case 16
              case 24: {
                int rawValue = input.readEnum();
                valueCase_ = 3;
                value_ = rawValue;
                break;
              } // case 24
              case 34: {
                input.readMessage(
                    getRequestErrorFieldBuilder().getBuilder(),
                    extensionRegistry);
                valueCase_ = 4;
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                valueCase_ = 5;
                value_ = s;
                break;
              } // case 42
              case 48: {
                isPush_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                rootSpanPtr_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int callbackIdx_ ;
      /**
       * <code>uint32 callback_idx = 1;</code>
       * @return The callbackIdx.
       */
      @java.lang.Override
      public int getCallbackIdx() {
        return callbackIdx_;
      }
      /**
       * <code>uint32 callback_idx = 1;</code>
       * @param value The callbackIdx to set.
       * @return This builder for chaining.
       */
      public Builder setCallbackIdx(int value) {

        callbackIdx_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 callback_idx = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCallbackIdx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        callbackIdx_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 resp_pointer = 2;</code>
       * @return Whether the respPointer field is set.
       */
      public boolean hasRespPointer() {
        return valueCase_ == 2;
      }
      /**
       * <code>uint64 resp_pointer = 2;</code>
       * @return The respPointer.
       */
      public long getRespPointer() {
        if (valueCase_ == 2) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }
      /**
       * <code>uint64 resp_pointer = 2;</code>
       * @param value The respPointer to set.
       * @return This builder for chaining.
       */
      public Builder setRespPointer(long value) {

        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 resp_pointer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRespPointer() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>.response.ConstantResponse constant_response = 3;</code>
       * @return Whether the constantResponse field is set.
       */
      @java.lang.Override
      public boolean hasConstantResponse() {
        return valueCase_ == 3;
      }
      /**
       * <code>.response.ConstantResponse constant_response = 3;</code>
       * @return The enum numeric value on the wire for constantResponse.
       */
      @java.lang.Override
      public int getConstantResponseValue() {
        if (valueCase_ == 3) {
          return ((java.lang.Integer) value_).intValue();
        }
        return 0;
      }
      /**
       * <code>.response.ConstantResponse constant_response = 3;</code>
       * @param value The enum numeric value on the wire for constantResponse to set.
       * @return This builder for chaining.
       */
      public Builder setConstantResponseValue(int value) {
        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.response.ConstantResponse constant_response = 3;</code>
       * @return The constantResponse.
       */
      @java.lang.Override
      public response.ResponseOuterClass.ConstantResponse getConstantResponse() {
        if (valueCase_ == 3) {
          response.ResponseOuterClass.ConstantResponse result = response.ResponseOuterClass.ConstantResponse.forNumber(
              (java.lang.Integer) value_);
          return result == null ? response.ResponseOuterClass.ConstantResponse.UNRECOGNIZED : result;
        }
        return response.ResponseOuterClass.ConstantResponse.OK;
      }
      /**
       * <code>.response.ConstantResponse constant_response = 3;</code>
       * @param value The constantResponse to set.
       * @return This builder for chaining.
       */
      public Builder setConstantResponse(response.ResponseOuterClass.ConstantResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueCase_ = 3;
        value_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.response.ConstantResponse constant_response = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConstantResponse() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          response.ResponseOuterClass.RequestError, response.ResponseOuterClass.RequestError.Builder, response.ResponseOuterClass.RequestErrorOrBuilder> requestErrorBuilder_;
      /**
       * <code>.response.RequestError request_error = 4;</code>
       * @return Whether the requestError field is set.
       */
      @java.lang.Override
      public boolean hasRequestError() {
        return valueCase_ == 4;
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       * @return The requestError.
       */
      @java.lang.Override
      public response.ResponseOuterClass.RequestError getRequestError() {
        if (requestErrorBuilder_ == null) {
          if (valueCase_ == 4) {
            return (response.ResponseOuterClass.RequestError) value_;
          }
          return response.ResponseOuterClass.RequestError.getDefaultInstance();
        } else {
          if (valueCase_ == 4) {
            return requestErrorBuilder_.getMessage();
          }
          return response.ResponseOuterClass.RequestError.getDefaultInstance();
        }
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      public Builder setRequestError(response.ResponseOuterClass.RequestError value) {
        if (requestErrorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          requestErrorBuilder_.setMessage(value);
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      public Builder setRequestError(
          response.ResponseOuterClass.RequestError.Builder builderForValue) {
        if (requestErrorBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          requestErrorBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      public Builder mergeRequestError(response.ResponseOuterClass.RequestError value) {
        if (requestErrorBuilder_ == null) {
          if (valueCase_ == 4 &&
              value_ != response.ResponseOuterClass.RequestError.getDefaultInstance()) {
            value_ = response.ResponseOuterClass.RequestError.newBuilder((response.ResponseOuterClass.RequestError) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 4) {
            requestErrorBuilder_.mergeFrom(value);
          } else {
            requestErrorBuilder_.setMessage(value);
          }
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      public Builder clearRequestError() {
        if (requestErrorBuilder_ == null) {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
          }
          requestErrorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      public response.ResponseOuterClass.RequestError.Builder getRequestErrorBuilder() {
        return getRequestErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      @java.lang.Override
      public response.ResponseOuterClass.RequestErrorOrBuilder getRequestErrorOrBuilder() {
        if ((valueCase_ == 4) && (requestErrorBuilder_ != null)) {
          return requestErrorBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 4) {
            return (response.ResponseOuterClass.RequestError) value_;
          }
          return response.ResponseOuterClass.RequestError.getDefaultInstance();
        }
      }
      /**
       * <code>.response.RequestError request_error = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          response.ResponseOuterClass.RequestError, response.ResponseOuterClass.RequestError.Builder, response.ResponseOuterClass.RequestErrorOrBuilder> 
          getRequestErrorFieldBuilder() {
        if (requestErrorBuilder_ == null) {
          if (!(valueCase_ == 4)) {
            value_ = response.ResponseOuterClass.RequestError.getDefaultInstance();
          }
          requestErrorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              response.ResponseOuterClass.RequestError, response.ResponseOuterClass.RequestError.Builder, response.ResponseOuterClass.RequestErrorOrBuilder>(
                  (response.ResponseOuterClass.RequestError) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 4;
        onChanged();
        return requestErrorBuilder_;
      }

      /**
       * <code>string closing_error = 5;</code>
       * @return Whether the closingError field is set.
       */
      @java.lang.Override
      public boolean hasClosingError() {
        return valueCase_ == 5;
      }
      /**
       * <code>string closing_error = 5;</code>
       * @return The closingError.
       */
      @java.lang.Override
      public java.lang.String getClosingError() {
        java.lang.Object ref = "";
        if (valueCase_ == 5) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 5) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string closing_error = 5;</code>
       * @return The bytes for closingError.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClosingErrorBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 5) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 5) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string closing_error = 5;</code>
       * @param value The closingError to set.
       * @return This builder for chaining.
       */
      public Builder setClosingError(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string closing_error = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClosingError() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string closing_error = 5;</code>
       * @param value The bytes for closingError to set.
       * @return This builder for chaining.
       */
      public Builder setClosingErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }

      private boolean isPush_ ;
      /**
       * <code>bool is_push = 6;</code>
       * @return The isPush.
       */
      @java.lang.Override
      public boolean getIsPush() {
        return isPush_;
      }
      /**
       * <code>bool is_push = 6;</code>
       * @param value The isPush to set.
       * @return This builder for chaining.
       */
      public Builder setIsPush(boolean value) {

        isPush_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_push = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsPush() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isPush_ = false;
        onChanged();
        return this;
      }

      private long rootSpanPtr_ ;
      /**
       * <code>optional uint64 root_span_ptr = 7;</code>
       * @return Whether the rootSpanPtr field is set.
       */
      @java.lang.Override
      public boolean hasRootSpanPtr() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint64 root_span_ptr = 7;</code>
       * @return The rootSpanPtr.
       */
      @java.lang.Override
      public long getRootSpanPtr() {
        return rootSpanPtr_;
      }
      /**
       * <code>optional uint64 root_span_ptr = 7;</code>
       * @param value The rootSpanPtr to set.
       * @return This builder for chaining.
       */
      public Builder setRootSpanPtr(long value) {

        rootSpanPtr_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 root_span_ptr = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRootSpanPtr() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rootSpanPtr_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:response.Response)
    }

    // @@protoc_insertion_point(class_scope:response.Response)
    private static final response.ResponseOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new response.ResponseOuterClass.Response();
    }

    public static response.ResponseOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public response.ResponseOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_RequestError_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_response_RequestError_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_response_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protobuf/response.proto\022\010response\"I\n\014R" +
      "equestError\022(\n\004type\030\001 \001(\0162\032.response.Req" +
      "uestErrorType\022\017\n\007message\030\002 \001(\t\"\203\002\n\010Respo" +
      "nse\022\024\n\014callback_idx\030\001 \001(\r\022\026\n\014resp_pointe" +
      "r\030\002 \001(\004H\000\0227\n\021constant_response\030\003 \001(\0162\032.r" +
      "esponse.ConstantResponseH\000\022/\n\rrequest_er" +
      "ror\030\004 \001(\0132\026.response.RequestErrorH\000\022\027\n\rc" +
      "losing_error\030\005 \001(\tH\000\022\017\n\007is_push\030\006 \001(\010\022\032\n" +
      "\rroot_span_ptr\030\007 \001(\004H\001\210\001\001B\007\n\005valueB\020\n\016_r" +
      "oot_span_ptr*O\n\020RequestErrorType\022\017\n\013Unsp" +
      "ecified\020\000\022\r\n\tExecAbort\020\001\022\013\n\007Timeout\020\002\022\016\n" +
      "\nDisconnect\020\003*\032\n\020ConstantResponse\022\006\n\002OK\020" +
      "\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_response_RequestError_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_RequestError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_response_RequestError_descriptor,
        new java.lang.String[] { "Type", "Message", });
    internal_static_response_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_response_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_response_Response_descriptor,
        new java.lang.String[] { "CallbackIdx", "RespPointer", "ConstantResponse", "RequestError", "ClosingError", "IsPush", "RootSpanPtr", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
