excludes:
    scopes:
        - pattern: "devDependencies"
          reason: "DEV_DEPENDENCY_OF"
          comment: "Packages for development only."
    paths:
        - pattern: "npm/glide/**"
          reason: "BUILD_TOOL_OF"
          comment: "Template file for CD"

        - pattern: "hybrid-node-tests/**"
          reason: "TEST_OF"
          comment: "Test files for hybrid node tests"
