#!/bin/bash
# This script add "type" and "types" entries to the different `package.json` that been created for `ECMAScript` and `CommonJS` with the fitting values.
cat >build-ts/cjs/package.json <<!EOF
{
    "type": "commonjs"
}
!EOF

cat >build-ts/mjs/package.json <<!EOF
{
    "type": "module"
}
!EOF
