/**
 * Copyright Valkey GLIDE Project Contributors - SPDX Identifier: Apache-2.0
 *
 * This entry point re-exports:
 * - Native bindings auto-generated by napi-rs (moved to ./native.js)
 * - All TypeScript client-side APIs from ./src/
 */

import * as Native from "./native";

export const {
    Level,
    MAX_REQUEST_ARGS_LEN,
    DEFAULT_REQUEST_TIMEOUT_IN_MILLISECONDS,
    DEFAULT_CONNECTION_TIMEOUT_IN_MILLISECONDS,
    DEFAULT_INFLIGHT_REQUESTS_LIMIT,
    AsyncClient,
    StartSocketConnection,
    log,
    InitInternalLogger,
    valueFromSplitPointer,
    createLeakedStringVec,
    Script,
    ClusterScanCursor,
    getStatistics,
} = Native;

// Export TypeScript APIs
export * from "./BaseClient.js";
export * from "./Batch.js";
export * from "./Commands.js";
export * from "./Errors.js";
export * from "./GlideClient.js";
export * from "./GlideClusterClient.js";
export * from "./Logger.js";
export * from "./server-modules/GlideFt.js";
export * from "./server-modules/GlideFtOptions.js";
export * from "./server-modules/GlideJson.js";
