excludes:
  scopes:
    - pattern: "//indirect"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Indirect dependencies used for development only."
    - pattern: "github.com/stretchr/testify"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Testing framework not included in production code."
  paths:
    - pattern: "integTest/**"
      reason: "TEST_OF"
      comment: "Integration test files not included in production code."
    - pattern: "benchmarks/**"
      reason: "TEST_TOOL_OF"
      comment: "Benchmark files used for performance testing only."
    - pattern: "examples/**"
      reason: "EXAMPLE_OF"
      comment: "Example code not included in production code."
    - pattern: ".*"
      reason: "BUILD_TOOL_OF"
      comment: "Hidden files used for build configuration."
    - pattern: "Makefile"
      reason: "BUILD_TOOL_OF"
      comment: "Build configuration file."
    - pattern: "DEVELOPER.md"
      reason: "DOCUMENTATION_OF"
      comment: "Developer documentation."
    - pattern: "rustbin/**"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Rust binary files used for building only."
