# Copyright Valkey GLIDE Project Contributors - SPDX Identifier: Apache-2.0
language = "C"

header = "/* Copyright Valkey GLIDE Project Contributors - SPDX Identifier: Apache-2.0 */"

[parse]
parse_deps = true
include = ["glide-core"] 
