[package]
name = "mock-glide-core-engine"
version = "0.1.0"
edition = "2024"

[dependencies]

# Mock crates for testing
glide-telemetry = { path = "../mock-glide-telemetry", package = "mock-glide-telemetry" }

# GLIDE dependencies
glide-core-engine = { path = "../../../glide-core/redis-rs/redis", features = ["aio", "tokio-comp", "tokio-rustls-comp"] }

# External dependencies
bytes = "1"
url = "2"
