name: Git Secrets Scan

runs:
    steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Install git-secrets
          run: |
              git clone --depth 1 --branch 1.3.0 https://github.com/awslabs/git-secrets.git
              cd git-secrets
              sudo make install

        - name: Configure git-secrets
          run: git secrets --register-aws

        - name: Run git-secrets
          run: git secrets --scan
