name: Lint rust

inputs:
    cargo-toml-folder:
        description: "folder that contains the target Cargo.toml file"
        required: true
        type: string
    github-token:
        description: "github token"
        required: false
        type: string

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

        - name: Install Rust toolchain
          uses: ./.github/actions/install-rust

        - name: Install protoc
          uses: ./.github/actions/install-protoc
          with:
              github-token: ${{ inputs.github-token }}

        - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
          with:
              path: ${{ inputs.cargo-toml-folder }}/target
              # this action should be used on the most common runner only
              key: x86_64-unknown-linux-gnu-${{ inputs.cargo-toml-folder }}

        - run: cargo fmt --all -- --check
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

        - run: cargo clippy --all-features --all-targets -- -D warnings
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

          # We run clippy without features
        - run: cargo clippy --all-targets -- -D warnings
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

        - run: |
              cargo install --locked cargo-deny
              cargo deny --config ${GITHUB_WORKSPACE}/deny.toml check
          working-directory: ${{ inputs.cargo-toml-folder }}
          shell: bash

        - name: doc
          shell: bash
          working-directory: ${{ inputs.cargo-toml-folder }}
          run: cargo doc --no-deps --document-private-items
          env:
              RUSTDOCFLAGS: -Dwarnings
