name: Create ephemeral self hosted EC2 runner

on:
    workflow_job:
        types: [queued]

jobs:
    create-ephemeral-self-hosted-runner:
        runs-on: ubuntu-latest
        if: |
            contains(join(fromJSON(toJSON(github.event.workflow_job.labels)), ','), 'self-hosted') &&
            contains(join(fromJSON(toJSON(github.event.workflow_job.labels)), ','), 'linux') &&
            contains(join(fromJSON(toJSON(github.event.workflow_job.labels)), ','), 'ARM64')
        steps:
            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Print comfirmation
              run: echo Role assumed
