name: Full Matrix tests

permissions:
    contents: read
    actions: write
    id-token: write

on:
    workflow_dispatch: # note: if started manually, it won't run all matrix
        inputs:
            full-matrix:
                description: "Run the full engine and host matrix"
                type: boolean
                default: true

            run-with-macos:
                description: "Run with macos inclauded (only when necessary)"
                type: choice
                options:
                    - false
                    - use-self-hosted
                    - use-github
                default: false

            run-modules-tests:
                description: "Run modules tests"
                type: boolean
                default: true

            # Rust crates
            core:
                description: "Test GLIDE core crates (core, engine, telemetry, logger)"
                type: boolean
                default: true
            ffi:
                description: "Test GLIDE FFI"
                type: boolean
                default: true

            # GLIDE clients
            rust:
                description: "Test Rust client"
                type: boolean
                default: true
            node:
                description: "Test Node client"
                type: boolean
                default: true
            python:
                description: "Test Python client"
                type: boolean
                default: true
            java:
                description: "Test Java client"
                type: boolean
                default: true
            go:
                description: "Test Golang client"
                type: boolean
                default: true

concurrency:
    group: nightly-${{ github.head_ref || github.ref }}-${{ toJson(inputs) }}
    cancel-in-progress: true

# TODO matrix by workflow (`uses`) - not supported yet by GH
jobs:
    check-input:
        runs-on: ubuntu-latest
        steps:
            - name: no tests selected
              run: false
              if: github.event_name == 'workflow_dispatch' && inputs.core == false && inputs.ffi == false && inputs.rust == false && inputs.node == false && inputs.python == false && inputs.java == false && inputs.go == false

    # --- Rust crate tests ---------------------------------------------------------------------- #

    run-full-tests-for-glide-logger:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.core == true)
        uses: ./.github/workflows/glide-logger.yml
        name: Run CI for glide-logger

    run-full-tests-for-glide-telemetry:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.core == true)
        uses: ./.github/workflows/glide-telemetry.yml
        name: Run CI for glide-telemetry

    run-full-tests-for-glide-core-engine:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.core == true)
        uses: ./.github/workflows/glide-core-engine.yml
        name: Run CI for glide-core-engine

    run-full-tests-for-glide-core:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.core == true)
        uses: ./.github/workflows/glide-core.yml
        with:
            run-with-macos: ${{ inputs.run-with-macos }}
        name: Run CI for glide-core

    run-full-tests-for-ffi:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.ffi == true)
        uses: ./.github/workflows/ffi.yml
        name: Run CI for FFI

    # --- Client tests -------------------------------------------------------------------------- #

    run-full-tests-for-rust:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.rust == true)
        uses: ./.github/workflows/rust.yml
        name: Run CI for Rust client

    run-full-tests-for-java:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.java == true)
        uses: ./.github/workflows/java.yml
        with:
            run-with-macos: ${{ inputs.run-with-macos }}
        name: Run CI for Java client

    run-full-tests-for-python:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.python == true)
        uses: ./.github/workflows/python.yml
        with:
            run-with-macos: ${{ inputs.run-with-macos }}
        name: Run CI for Python client

    run-full-tests-for-node:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.node == true)
        uses: ./.github/workflows/node.yml
        with:
            run-with-macos: ${{ inputs.run-with-macos }}
        name: Run CI for Node client

    run-full-tests-for-go:
        if: (github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.go == true)
        uses: ./.github/workflows/go.yml
        name: Run CI for go client

    # --- Client module tests ------------------------------------------------------------------- #

    run-modules-tests-for-java:
        if: ((github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.run-modules-tests == true)) && inputs.java != false
        uses: ./.github/workflows/java-modules.yml
        name: Run modules tests for java client
        secrets:
            MEMDB_MODULES_ENDPOINT: ${{ secrets.MEMDB_MODULES_ENDPOINT }}

    run-modules-tests-for-python:
        if: ((github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.run-modules-tests == true)) && inputs.python != false
        uses: ./.github/workflows/python-modules.yml
        name: Run modules tests for python client
        secrets:
            MEMDB_MODULES_ENDPOINT: ${{ secrets.MEMDB_MODULES_ENDPOINT }}

    run-modules-tests-for-node:
        if: ((github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.run-modules-tests == true)) && inputs.node != false
        uses: ./.github/workflows/node-modules.yml
        name: Run modules tests for node client
        secrets:
            MEMDB_MODULES_ENDPOINT: ${{ secrets.MEMDB_MODULES_ENDPOINT }}

    run-modules-tests-for-go:
        if: ((github.repository_owner == 'valkey-io' && github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.run-modules-tests == true)) && inputs.go != false
        uses: ./.github/workflows/go-modules.yml
        name: Run modules tests for go client
        secrets:
            MEMDB_MODULES_ENDPOINT: ${{ secrets.MEMDB_MODULES_ENDPOINT }}
