name: Java Tests (Self-Hosted)

on:
    workflow_dispatch:
        inputs:
            java-version:
                description: "Java version to test"
                required: false
                default: "17"
                type: choice
                options:
                    - "11"
                    - "17"
            engine-version:
                description: "Valkey engine version"
                required: false
                default: "8.0.1"
                type: string

jobs:
    test-self-hosted:
        name: Java ${{ github.event.inputs.java-version }} on Self-Hosted Linux
        runs-on: [self-hosted, linux, valkey-runner] # Target your labeled runner
        timeout-minutes: 35

        steps:
            - name: Setup self-hosted runner access
              run: sudo chown -R $USER:$USER ${{ github.workspace }}

            - uses: actions/checkout@v4

            - name: Set up JDK ${{ github.event.inputs.java-version }}
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: ${{ github.event.inputs.java-version }}

            - name: Install protoc (protobuf)
              uses: arduino/setup-protoc@v3
              with:
                  version: "29.1"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install shared software dependencies
              uses: ./.github/workflows/install-shared-dependencies
              with:
                  os: ubuntu
                  target: x86_64-unknown-linux-gnu
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  engine-version: ${{ github.event.inputs.engine-version }}
                  language: java

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Build Java client
              working-directory: java
              run: ./gradlew --build-cache --continue build -x javadoc

            - name: Run integration tests
              working-directory: java
              run: ./gradlew --build-cache :integTest:test

            - name: Upload test reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: java-test-reports-self-hosted
                  path: |
                      java/client/build/reports/**
                      java/integTest/build/reports/**
