name: Rust tests

on:
    push:
    pull_request:
        paths:
            - logger_core/**
            - glide-core/**
            - glide-core/redis-rs/redis/src/**
            - utils/cluster_manager.py
            - .github/workflows/rust.yml
            - .github/workflows/install-shared-dependencies/action.yml
            - .github/workflows/install-engine/action.yml
            - .github/workflows/lint-rust/action.yml
            - .github/workflows/create-test-matrices/action.yml
            - .github/json_matrices/**
            - deny.toml
    workflow_dispatch:
        inputs:
            full-matrix:
                description: "Run the full engine and host matrix"
                type: boolean
                default: false
            name:
                required: false
                type: string
                description: "(Optional) Test run name"

    workflow_call:

concurrency:
    group: rust-${{ github.head_ref || github.ref }}-${{ toJson(inputs) }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

run-name:
    # Set custom name if job is started manually and name is given
    ${{ github.event_name == 'workflow_dispatch' && (inputs.name == '' && format('{0} @ {1} {2}', github.ref_name, github.sha, toJson(inputs)) || inputs.name) || '' }}

jobs:
    get-matrices:
        runs-on: ubuntu-latest
        # Avoid running on schedule for forks
        if: (github.repository_owner == 'valkey-io' || github.event_name != 'schedule') || github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

        steps:
            - uses: actions/checkout@v4

            - uses: actions/cache/restore@v4
              with:
                  key: v0-rust-x86_64-unknown-linux-gnu-glide-core-Linux-c733e78c-b62606ca
                  path: cacache

            - uses: actions/upload-artifact@v4
              with:
                  path: cacache
